### ISSUE TITLE
这个地方为啥要唤醒两次，前面那次我知道为啥。后面那次是多余的吗？

### ISSUE THREAD

**Issue by smith397** [waylau/netty-4-user-guide-demos#14]
public void run() {
		SocketChannel socketChannel;
		try {
			socketChannel = serverSocketChannel.accept(); // 连接
			if (socketChannel != null) {
				System.out.println(String.format("accpet %s", socketChannel.getRemoteAddress()));
				socketChannel.configureBlocking(false);

				// 注意一个selector在select时是无法注册新事件的，因此这里要先暂停下select方法触发的程序段，
				// 下面的weakup和这里的setRestart都是做这个事情的，具体参考SubReactor里的run方法
				reactors[next].registering(true);
				selectors[next].wakeup(); // 使一个阻塞住的selector操作立即返回
				SelectionKey selectionKey = 
						socketChannel.register(selectors[next], SelectionKey.OP_READ); // 注册一个读事件
				selectors[next].wakeup(); // 使一个阻塞住的selector操作立即返回

				// 本次事件注册完成后，需要再次触发select的执行，
				// 因此这里Restart要在设置回false（具体参考SubReactor里的run方法）
				reactors[next].registering(false);

				// 绑定Handler
				selectionKey.attach(new AsyncHandler(socketChannel, selectors[next], next));
				if (++next == selectors.length) {
					next = 0;    // 越界后重新分配
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

**Comment by waylau** [comment]
@smith397 
因为“本次事件注册完成后，需要再次触发select的执行”

简言之，每次执行select前都做一次wakeup。
