### ISSUE TITLE
第一章示例，client相关参数建议配置到ide当中

### ISSUE THREAD

**Issue by DestinyL** [waylau/netty-4-user-guide-demos#18]
1. 参考如图
![image](https://user-images.githubusercontent.com/7259482/110281361-8c37c380-8017-11eb-8ed3-53e8c8d0df04.png)
2. 配置到ide当中运行示例不用每次去敲一遍（关闭之后，如果没有关闭可以使用历史）

**Comment by waylau** [comment]
@DestinyL 

感谢反馈，已经登记。 see https://github.com/waylau/netty-4-user-guide-demos/issues/15
