### ISSUE TITLE
使用Object编解码器后client 连接不能自动关闭

### ISSUE THREAD

**Issue by MrYang** [waylau/netty-4-user-guide-demos#2]
你好，我在运行codec包中的server及client过程中，启动SerializationClient 发送消息完成后，该client并没有自动关闭，代码一直挺在`channel.closeFuture().sync()`这里，请问下怎么样才能让该client自动关闭。运行其他工程，如echo,time则不会出现这种情况

**Comment by MrYang** [comment]
接上，其他的demo如time，echo，都没有这种现象，client运行完后会自动关闭。

**Comment by waylau** [comment]
channel.closeFuture().sync(); 是异步的关闭，会一直阻塞在 main 的线程。你 注释掉这句 就行了。~
