### ISSUE TITLE
43页调用 selectedKeySet()的 对象应该是Selector

### ISSUE THREAD

**Issue by liliuming-truism** [waylau/netty-4-user-guide-demos#20]
在43页说明获取SelectionKey就绪集合时应该是通过Selector的selectedKeySet()方法，而不是SelectionKey。

**Comment by waylau** [comment]
@liliuming-truism  感谢反馈，我回头确认下

**Comment by waylau** [comment]
@liliuming-truism 感谢! 问题已经归档 https://github.com/waylau/netty-4-user-guide-demos/issues/15
