### ISSUE TITLE
书籍p34页错误，帮我确认是否购买的盗版书籍？

### ISSUE THREAD

**Issue by joraboy328** [waylau/netty-4-user-guide-demos#25]
参考书籍p33页例子手敲代码，第p34页错误.

        try {
            // 启动NOI服务器的引导程序类
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup,workGroup)
                    .channel(NioServerSocketChannel.class)
                    .childHandler(new EchoServerHandler())
                    .option(ChannelOption.SO_BACKLOG,128)
                    .childOption(ChannelOption.SO_KEEPALIVE,true);
            ChannelFuture f = b.bind(port).sync();//未处理 异常: java.lang.InterruptedException

            f.channel().closeFuture().sync();//未处理 异常: java.lang.InterruptedException
        } finally {
                workGroup.shutdownGracefully();
                bossGroup.shutdownGracefully();
        }

**Comment by waylau** [comment]
你这个代码片段，看着没啥问题。
本书提供全套源码，你可以对比下完整的源码，看是否有错漏。

https://github.com/waylau/netty-4-user-guide-demos/blob/master/netty4-demos/src/main/java/com/waylau/netty/demo/echo/EchoServer.java
